### ISSUE TITLE
Swap out GPL for AGPL

### ISSUE THREAD

**Issue by day** [patrik-u/circles#2]
Hey @patrik-u, I think it's important that we use the AGPL rather than the basic GPL because: "The AGPL license differs from the other GNU licenses in that it was built for network software. You can distribute modified versions if you keep track of the changes and the date you made them. As per usual with GNU licenses, you must license derivatives under AGPL. It provides the same restrictions and freedoms as the GPLv3 but with an additional clause which makes it so that source code must be distributed along with web publication. Since web sites and services are never distributed in the traditional sense, the AGPL is the GPL of the web." https://opensource.org/licenses/AGPL-3.0

**Comment by patrik-u** [comment]
Done.
